# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d265a3bb18c6a16ff56cc9aa5267bb8"
name = "wishlist"
application_url = "https://platform-citations-island-obvious.trycloudflare.com"
embedded = true
handle = "wishlist-900"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://platform-citations-island-obvious.trycloudflare.com/auth/callback", "https://platform-citations-island-obvious.trycloudflare.com/auth/shopify/callback", "https://platform-citations-island-obvious.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
