name = "wishlist-icon"
type = "theme"
uid = "23cc0911-4903-ae58-b04a-1a7627eee9a0470e04c9"

[build]
command = "npm run build"
path = "extensions/add-to-wishlist-icon"

[dev]
command = "npm run dev"
path = "extensions/add-to-wishlist-icon"

[[blocks]]
name   = "Wishlist Button"
target = "product-card"         # or "product" if you prefer
path   = "blocks/wishlist-btn.liquid"

[[blocks]]
name   = "Wishlist Page"
target = "page"
path   = "blocks/wishlist-page.liquid"


[[blocks]]
name   = "Heart Icon"
target = "product-card"
path   = "blocks/heart-icon.liquid"